### ISSUE TITLE
Weighted Spectral Distance(WESD)

### ISSUE THREAD

**Issue by msrepo** [naamiinepal/xrayto3D-benchmark#13]
#### Description
WESD between two binary segmentations is pose-invariant. This could be useful as a metric for retrieval-based methods. Current Implementation of Image-Space metrics such as DSC, ASD, HD are pose-sensitive.

#### Literature
[ Anatomy-Aware Inference of the 3D Standing Spine Posture from 2D Radiographs ](https://www.mdpi.com/2379-139X/8/1/39)
[WESD - Weighted Spectral Distance for Measuring Shape Dissimilarity](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5513679/)
[Discriminative Segmentation-based Evaluation through Shape Dissimilarity](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5507673/)
[Martin Reuter et al.
Laplace-Beltrami spectra as "Shape-DNA" of surfaces and solids
Computer-Aided Design 38(4):342-366, 2006](https://core.ac.uk/download/pdf/56378631.pdf)
[Discrete Laplace-Beltrami Operators for Shape Analysis and Segmentation](https://www.researchgate.net/publication/222524751_Discrete_Laplace-Beltrami_operators_for_shape_analysis_and_segmentation)

#### Reference
[laplace-beltrami operation implementation](https://github.com/nipy/mindboggle/blob/master/mindboggle/shapes/laplace_beltrami.py)
[Numerical Methods for Partial Differential Equations, Ames,Chapter 2]
[Arnoldi's Method for eigenvalues of sparse matrix](https://github.com/rngantner/Arnoldi_PyCpp)

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Compute the Laplace-Beltrami spectrum using a linear finite element method
- [ ] compute eigenvalues via Arnoldi's method
- [ ] choose p,N for nWSD (N=200,p=2.0 for 3D was found to be good choice) and normalize WSD
