### ISSUE TITLE
Evaluation gaps in ML Practice: table

### ISSUE THREAD

**Issue by msrepo** [naamiinepal/xrayto3D-benchmark#14]
#### Description
![image](https://user-images.githubusercontent.com/10219364/236612241-265df914-6b35-46f0-b6d7-cc9fc3e19315.png)
A Table for Evaluation gaps in Biplanar X-ray to 3D Segmentation similar to the above table will help argument for the paper and give evidence for evaluation gaps.

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] List relevant papers
- [ ] define rows and columns for the table
- [ ] fill up the table
